### ISSUE TITLE
能添加行程吗？

### ISSUE THREAD

**Issue by MarkerBrother** [maning0303/MNCalendar#1]
类似于添加行程等，可以在日历上显示出来

**Comment by maning0303** [comment]
现在没有这个功能，这种功能挺容易的，你改一下源码判断日期显示UI的就可以了！

**Comment by MarkerBrother** [comment]
谢谢啊。。。我找个时间看看



shennanshenqin@163.com
 
发件人： 马宁
发送时间： 2017-05-27 15:40
收件人： maning0303/MNCalendar
抄送： nan_shen; Author
主题： Re: [maning0303/MNCalendar] 能添加行程吗？ (#1)
现在没有这个功能，这种功能挺容易的，你改一下源码判断日期显示UI的就可以了！
